language: ruby
sudo: true
rvm:
- 2.1
install:
- bundle install --jobs=3 --retry=3
- sudo apt-get update -qq
- sudo apt-get install -qq libgc1c2
- chmod +x ./build/* && "./build/haxe-setup.sh"
before_script: bundle update
script: bundle exec rake deploy
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - NEKOPATH=$HOME/neko
  - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$NEKOPATH
  - PATH=$PATH:$NEKOPATH
  - PATH=$PATH:$HOME/haxe
  - HAXE_STD_PATH=$HOME/haxe/std
  - secure: I3XvvxHmvPcmggemzLbLNBcqwchKSAc/94I02DWa/f/e9JwKu1ePJz4fTfozFBXoNV3fra836+gx8mnvg3otpMGrnmx5qup02dVKMVCAltHeUgMI2nZ2c2sZSbh2P0kSf9wVff31c6pqdRwVPB5JZEfNtZFUNQv2w6RHzam0+sovKuAiG7EFYSFbZ+e/ItDtt3JbMmELO/ptgOsS5fdVyXwPAH9mqBhjLJfGfYSLTqKhSXJVa5ZOQ80k/XjerhB3lwhjGIVxTU5KD9jg9+F6m86t0zXOyF0i+fT/9P8I3RGl97FP6AlBOYajPQ79xgzmgdHZ82g72V8cVdFpCdI6AmujwZFuVfR8PrZ7tnBFsVEuc7SVuueuqOx0yuB5ybuR/Dupw84GM3ibN01UFkQTqGp5jMk10RqVrwtYU/C4r3D64axlGw60rSqiyEmgoUKQ6xRAKec6hW6RCJTC97ohnCW+zTbRIPrk5voT2hpE2Pr4q6vtGAPaaKPqX9NHjbabMnuHAeYTre34WEmDHMdy1wEUGC+4sA6oO4ufr4jaNtbRxXytC8DFyHqvSZbVatBMARGI5vRrSatziK/aDYRq8fo1C4UTfUgF8tH1g+/ReEP/cXCeMAFuicLDp4OZQlCfK+NyK7VD9zfSIwPMu+P14Owi0qsq8NbHjdWtmk5mQOI=
branches:
  only:
  - master
after_success: if [[ "$TRAVIS_REPO_SLUG" == "SeiferTim/hf-january" ]]; then bundle exec
  ruby ./build/serversync.rb; fi
