language: ruby
sudo: true
rvm:
- 2.1
install:
- bundle install --jobs=3 --retry=3
- sudo apt-get update -qq
- sudo apt-get install -qq libgc1c2
- chmod +x ./build/* && "./build/haxe-setup.sh"
before_script: bundle update
script: bundle exec rake deploy
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - NEKOPATH=$HOME/neko
  - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$NEKOPATH
  - PATH=$PATH:$NEKOPATH
  - PATH=$PATH:$HOME/haxe
  - HAXE_STD_PATH=$HOME/haxe/std
  - secure: J2SFFjbKQwpLB5uZzjrvwRjVpHnHhRCDNsigt1bERLTbvRUTQOvWhKPuMOk4Rs/2CwfCkkST8NyoP5h7ymGVFahc6t3yd8LljHNZyo7dmkQD4zfPBr5uoGnCVOcF1GbWhnNhBNGK/6INRDFBJ768wzb437K+oUP1m1nli0RPNGcCwIJjCXaJtvsVJjnbiBMGDYx2O01+m7zqYvZ6PkQ7QXZ8uxgWaLID7JQBWDGXVeGqiFC8EotG28REaplz5ouahvLphSdRaLQli1WYPjA9wg7Zz05UnlUtWWeNuVthTB9gInCe0t3pFC9eQzQ3NuiUevnUjXleDnolFRPYqcwAJyR3uyNXlGByifAM3Wvj8NF+5TdorS0wMrpIG4o6ShYgDt7C91UnkEI6KwhsKq+MWo/6sk2ZgcJv8EZHY4r4fsS92rn8eza3sv2QWPumAJsnojj7RRnh6FRjNH0Ei6nysSWDd5hPO07fL529dTK7K2fDOkcW7EHC4S3TdcN197TGbUv33FwRxSCU5St1ho+vpOae9cE121BLTpQVSnDD2Ip/uXdCjioAIysuu3YsLrYUHjkDGMURKd6bOHWzSrDjqeBiStA6b+bGBTnK7f/lgaPgv+FdkGrGXEcR9OnkCLVv0uGVHgtLkhQMm99rn88cM83CLTizNE4ANQQlnlAn1hY=
branches:
  only:
  - master
after_success: if [[ "$TRAVIS_REPO_SLUG" == "SeiferTim/hf-january" ]]; then bundle
  exec ruby ./build/serversync.rb; fi
